//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSyntax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarSyntax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keepInMemory yes,no
        ///inBackground yes,no
        ///blockingRegionsDuringBlackout yes,no
        ///resetAfterEnter yes,no
        ///spotlight yes,no
        ///actionType none,border,transitionToScene,move,resetRegion,resetScene
        ///animationType none,sizeChanging,rotationCounterclockwise,rotationClockwise,swingingHorizontal,swingingVertical
        ///fontStyle i,b,u,s
        ///turnOffWhenFinished yes,no
        ///regionAnimationEnabled yes,no
        ///imageAnimationEnabled yes,no
        ///conditionOfReactionCompletion regionLeave,soundEnding,timeElapsed
        ///holdSceneTransitionUntillReaction [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttributesStatment {
            get {
                return ResourceManager.GetString("AttributesStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giml
        ///GIML
        ///settings folder,language,library
        ///activation actionType,borderWidth,borderColor,nameOfTargetScene,nameOfImage,nameOfSound,path,speed,animationType,animationAmplitude,animationPeriod,tag,delayedTag,delayOfDelayedTag,text,font,fontSize,fontStyle,fontColor,turnOffWhenFinished,nameOfRegionEnabledWhenStarted,nameOfRegionDisabledWhenStarted,nameOfRegionEnabledWhenFinished,nameOfRegionDisabledWhenFinished
        ///reaction action,actionType,borderWidth,borderColor,nameOfTargetScene,nameOfImage,nameOfSound,path [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeywordsStatment {
            get {
                return ResourceManager.GetString("KeywordsStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to markup giml
        ///giml settings,giml
        ///settings image/,images,list/,lists,movie,scene,scenes,sound,settings
        ///images image/,images
        ///lists list,lists
        ///movie settings,activation,reaction,list,lists,region,scene,scenes,sound,movie
        ///region activation,reaction,list,lists,movie,scene,scenes,sound,region
        ///scene activation,reaction,movie,region,sound,scene
        ///scenes scene,scenes
        ////region activation,reaction,movie,region,sound
        ////images image/,images,list/,lists,movie,scene,scenes,sound,settings
        ////scenes image/,images,list/,l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarkupNesting {
            get {
                return ResourceManager.GetString("MarkupNesting", resourceCulture);
            }
        }
    }
}
